apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: lobby
spec:
  clusterRef:
    name: home
  replicas: 1
  template:
    spec:
      clusterRef:
        name: home
      tags:
        - lobby
      version:
        channel: Paper
        # Use a specific supported version for Paper. This is the example from docs.
        # Change to your target Minecraft version (e.g. '1.21.1') when ready.
        name: '1.20.2'
      config: {}
