apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: paper
spec:
  clusterRef:
    name: home
  replicas: 2
  template:
    spec:
      clusterRef:
        name: home
      tags:
        - survival
      version:
        channel: Paper
        name: '1.20.2'
      config: {}
