apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet
metadata:
  name: public
spec:
  clusterRef:
    name: home
  replicas: 1
  service:
    # If you don't have a LoadBalancer in your homelab, change this to NodePort
    # or install MetalLB.
    type: LoadBalancer
    externalTrafficPolicy: Local
  template:
    spec:
      version:
        channel: Velocity
        name: latest
      config: {}
