apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: agones-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: shulker-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: mc
