apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: home
  namespace: argocd
spec:
  description: "Home cluster GitOps project"
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
